# Cloned from @tesla/particles .sass-lint.yml
# 
options:
  # To output to terminal, perform the following:
  #   change formatter to `stylish`
  #   comment `output-file`
  #formatter: html
  #output-file: 'linters/sass-lint.html'
  formatter: 'stylish'

  merge-default-rules: false
files:
  include:
    - 'styleguide_assets/**/*.s+(a|c)ss'
    - 'scss/**/*.s+(a|c)ss'
  ignore:
    - 'styleguide/**/*.s+(a|c)ss'
rules:
  # Extends
  extends-before-mixins: 1
  extends-before-declarations: 1
  placeholder-in-extend: 1

  # Mixins
  mixins-before-declarations: 1

  # Line Spacing
  one-declaration-per-line: 1
  empty-line-between-blocks: 1
  single-line-per-selector: 1

  # Disallows
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 1
  no-color-literals: 1
  no-combinators: 0
  no-css-comments: 0
  no-debug: 0
  no-disallowed-properties: 0
  no-duplicate-properties: 1
  no-empty-rulesets: 1
  no-extends: 0
  no-ids: 1
  no-important: 0
  no-invalid-hex: 1
  no-mergeable-selectors: 1
  no-misspelled-properties:
    - 2
    - 'extra-properties':
      - 'overflow-scrolling'
  no-qualifying-elements: 1
  no-trailing-whitespace: 1
  no-trailing-zero: 0
  no-transition-all: 0
  no-universal-selectors: 0
  no-url-domains: 0 # TODO: re-enable this when possible
  no-url-protocols: 0 # TODO: re-enable this backup images have been removed
  no-vendor-prefixes: 0
  no-warn: 0
  property-units: 0

  # Nesting
  declarations-before-nesting: 1
  force-attribute-nesting: 1
  force-element-nesting: 1
  force-pseudo-nesting: 0 # TODO: reenable

  # Name Formats
  class-name-format: 0 # TODO: enable name format

  # TODO: re-enable after the following have been renamed:
  #   calculateRem
  function-name-format: 0
  id-name-format: 0

  # TODO: re-enable after the following have been renamed:
  #   fontParams
  #   zIndex
  #   calculateRem
  mixin-name-format: 0
  placeholder-name-format: 1
  variable-name-format: 0

  # Style Guide
  attribute-quotes: 1
  bem-depth: 0
  border-zero: 1
  brace-style: 1
  clean-import-paths: 1
  empty-args: 1
  hex-length: 1
  hex-notation: 1
  indentation: 1
  leading-zero: 1
  max-line-length: 0
  max-file-line-count: 0
  nesting-depth:
    - 1
    - max-depth: 5
  property-sort-order:
    - 1
    - order:
      - concentric
  pseudo-element: 1
  quotes: 1
  shorthand-values: 1
  url-quotes: 1
  variable-for-property: 1
  zero-unit: 1

  # Inner Spacing
  space-after-comma: 1
  space-before-colon: 1
  space-after-colon: 1
  space-before-brace: 1
  space-before-bang: 1
  space-after-bang: 1
  space-between-parens: 1
  space-around-operator: 1

  # Final Items
  trailing-semicolon: 1
  final-newline: 1